-- MedTrack Supabase/Postgres bootstrap
-- Run this in Supabase SQL Editor before starting the API/worker.

-- ==========================================
-- 1. CORE ACTOR HIERARCHY
-- ==========================================
CREATE TABLE IF NOT EXISTS ACTOR (
    actor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    role_type TEXT NOT NULL CHECK (role_type IN ('Manufacturer', 'Pharmacy', 'Admin', 'Customer')),
    registered_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS MANUFACTURER (
    actor_id INTEGER PRIMARY KEY,
    license_no VARCHAR(50) NOT NULL UNIQUE,
    production_capacity INTEGER,
    FOREIGN KEY (actor_id) REFERENCES ACTOR(actor_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PHARMACY (
    actor_id INTEGER PRIMARY KEY,
    pharmacy_license VARCHAR(50) NOT NULL UNIQUE,
    gps_lat NUMERIC(10, 8) NOT NULL,
    gps_long NUMERIC(11, 8) NOT NULL,
    FOREIGN KEY (actor_id) REFERENCES ACTOR(actor_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ADMIN (
    actor_id INTEGER PRIMARY KEY,
    security_clearance_level INTEGER DEFAULT 1,
    FOREIGN KEY (actor_id) REFERENCES ACTOR(actor_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CUSTOMER (
    actor_id INTEGER PRIMARY KEY,
    phone_number VARCHAR(20) UNIQUE,
    device_id VARCHAR(128),
    FOREIGN KEY (actor_id) REFERENCES ACTOR(actor_id) ON DELETE CASCADE
);

-- ==========================================
-- 2. CORE DATA ENTITIES
-- ==========================================
CREATE TABLE IF NOT EXISTS MEDICINE (
    medicine_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    generic_name VARCHAR(100) NOT NULL,
    brand_name VARCHAR(100) NOT NULL,
    base_price NUMERIC(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS BATCH (
    batch_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_id INTEGER NOT NULL,
    qr_code_hash VARCHAR(64) NOT NULL UNIQUE,
    mfg_date DATE NOT NULL,
    expiry_date DATE NOT NULL,
    current_owner_id INTEGER NOT NULL,
    FOREIGN KEY (medicine_id) REFERENCES MEDICINE(medicine_id) ON DELETE RESTRICT,
    FOREIGN KEY (current_owner_id) REFERENCES ACTOR(actor_id) ON DELETE RESTRICT
);

-- ==========================================
-- 3. ACTION ENTITIES
-- ==========================================
CREATE TABLE IF NOT EXISTS INVENTORY (
    pharmacy_id INTEGER NOT NULL,
    batch_id INTEGER NOT NULL,
    quantity_on_hand INTEGER NOT NULL DEFAULT 0,
    last_updated TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (pharmacy_id, batch_id),
    FOREIGN KEY (pharmacy_id) REFERENCES PHARMACY(actor_id) ON DELETE CASCADE,
    FOREIGN KEY (batch_id) REFERENCES BATCH(batch_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TRANSFER_LOG (
    transfer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id INTEGER NOT NULL,
    sender_id INTEGER NOT NULL,
    receiver_id INTEGER NOT NULL,
    transfer_date TIMESTAMPTZ DEFAULT NOW(),
    status TEXT DEFAULT 'Initiated' CHECK (status IN ('Initiated', 'In-Transit', 'Received', 'Rejected')),
    FOREIGN KEY (batch_id) REFERENCES BATCH(batch_id) ON DELETE RESTRICT,
    FOREIGN KEY (sender_id) REFERENCES ACTOR(actor_id) ON DELETE RESTRICT,
    FOREIGN KEY (receiver_id) REFERENCES ACTOR(actor_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS SALE_TRANSACTION (
    txn_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pharmacy_id INTEGER NOT NULL,
    batch_id INTEGER NOT NULL,
    quantity_sold INTEGER NOT NULL,
    sale_timestamp TIMESTAMPTZ DEFAULT NOW(),
    treatment_duration_days INTEGER,
    override_reason VARCHAR(255),
    FOREIGN KEY (pharmacy_id) REFERENCES PHARMACY(actor_id) ON DELETE RESTRICT,
    FOREIGN KEY (batch_id) REFERENCES BATCH(batch_id) ON DELETE RESTRICT
);

-- ==========================================
-- 4. SECURITY/ANOMALY ENTITIES
-- ==========================================
CREATE TABLE IF NOT EXISTS SCAN_LOG (
    scan_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id INTEGER NOT NULL,
    scanned_by INTEGER NOT NULL,
    gps_lat NUMERIC(10, 8) NOT NULL,
    gps_long NUMERIC(11, 8) NOT NULL,
    scan_timestamp TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (batch_id) REFERENCES BATCH(batch_id) ON DELETE CASCADE,
    FOREIGN KEY (scanned_by) REFERENCES ACTOR(actor_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ALERT (
    alert_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id INTEGER NOT NULL,
    alert_type TEXT NOT NULL CHECK (alert_type IN ('Geo-Anomaly', 'Expired-Attempt', 'Counterfeit-Flag')),
    severity TEXT NOT NULL CHECK (severity IN ('Low', 'Medium', 'High')),
    alert_timestamp TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (batch_id) REFERENCES BATCH(batch_id) ON DELETE CASCADE
);

-- ==========================================
-- 5. INDEXES
-- ==========================================
CREATE INDEX IF NOT EXISTS idx_batch_expiry ON BATCH(expiry_date);
CREATE UNIQUE INDEX IF NOT EXISTS idx_qr_hash ON BATCH(qr_code_hash);

-- ==========================================
-- 6. SUPPORT TRIGGERS
-- ==========================================
CREATE OR REPLACE FUNCTION set_inventory_last_updated()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.last_updated = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_inventory_last_updated ON INVENTORY;
CREATE TRIGGER trg_inventory_last_updated
BEFORE UPDATE ON INVENTORY
FOR EACH ROW
EXECUTE FUNCTION set_inventory_last_updated();

-- ==========================================
-- 7. SALE PROCESSING FUNCTION
-- Mirrors previous PROCESS_SALE behavior used by API
-- ==========================================
CREATE OR REPLACE FUNCTION process_sale(
    p_pharmacy_id INTEGER,
    p_batch_id INTEGER,
    p_qty INTEGER,
    p_duration INTEGER,
    p_reason VARCHAR
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
    v_stock INTEGER;
    v_risk_score INTEGER := 0;
    v_distinct_pharmacies INTEGER := 0;
    v_expiry DATE;
BEGIN
    IF p_qty IS NULL OR p_qty <= 0 THEN
        RAISE EXCEPTION 'Field ''quantity'' must be > 0';
    END IF;

    -- Rule 1: velocity/cloning check from recent scans.
    SELECT COUNT(DISTINCT scanned_by)
    INTO v_distinct_pharmacies
    FROM SCAN_LOG
    WHERE batch_id = p_batch_id
      AND scan_timestamp >= NOW() - INTERVAL '24 hours';

    IF v_distinct_pharmacies > 1 THEN
        v_risk_score := v_risk_score + 80;
    END IF;

    IF v_risk_score >= 50 THEN
        RAISE EXCEPTION 'Transaction Blocked: High Counterfeit Risk Score (Duplicate geographic scans detected).';
    END IF;

    -- Lock current stock row.
    SELECT quantity_on_hand
    INTO v_stock
    FROM INVENTORY
    WHERE pharmacy_id = p_pharmacy_id
      AND batch_id = p_batch_id
    FOR UPDATE;

    IF v_stock IS NULL OR v_stock < p_qty THEN
        RAISE EXCEPTION 'Insufficient stock for this batch.';
    END IF;

    SELECT expiry_date
    INTO v_expiry
    FROM BATCH
    WHERE batch_id = p_batch_id;

    IF v_expiry IS NULL THEN
        RAISE EXCEPTION 'Batch not found for provided batch_id.';
    END IF;

    IF v_expiry < CURRENT_DATE AND (p_reason IS NULL OR BTRIM(p_reason) = '') THEN
        RAISE EXCEPTION 'Transaction Blocked: Medicine is expired. Admin override reason required.';
    END IF;

    UPDATE INVENTORY
    SET quantity_on_hand = quantity_on_hand - p_qty
    WHERE pharmacy_id = p_pharmacy_id
      AND batch_id = p_batch_id;

    INSERT INTO SALE_TRANSACTION (
        pharmacy_id,
        batch_id,
        quantity_sold,
        treatment_duration_days,
        override_reason
    )
    VALUES (
        p_pharmacy_id,
        p_batch_id,
        p_qty,
        p_duration,
        p_reason
    );
END;
$$;
